/*
* Generated file
*
* Generated from: yang module name: pool-service-impl yang module local name: pool-service-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 13 15:31:25 EST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.pool_service.impl;

import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.pool.service.impl.rev140131.AbstractPoolServiceModuleFactory;

public class PoolServiceModuleFactory extends AbstractPoolServiceModuleFactory {

}
